name = "send-to-paperless"
main = "src/worker.ts"
compatibility_date = "2024-10-26"
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1

[vars]
PAPERLESS_API_BASE = "https://paperless.cmdcentral.xyz/api"
